In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
 %pip install keras_preprocessing

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 3.1 MB/s eta 0:00:00


In [ ]:
from keras_preprocessing.text import one_hot
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten,Embedding


In [ ]:
df = pd.read_csv("/content/sample_data/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
print(X_train)

2245                              No management puzzeles.
1820                Dunno dat's wat he told me. Ok lor...
642     said kiss, kiss, i can't do the sound effects!...
1726    You know there is. I shall speak to you in  &l...
3105    That's y i said it's bad dat all e gals know u...
                              ...                        
2985    He said that he had a right giggle when he saw...
3789    Want to funk up ur fone with a weekly new tone...
3392                   I'm in a meeting, call me later at
5054                          Lmao you know me so well...
1227    Reply with your name and address and YOU WILL ...
Name: Message, Length: 4457, dtype: object


In [ ]:
print(X_test)

3238    Ron say fri leh. N he said ding tai feng cant ...
2414    Lol please do. Actually send a pic of yourself...
4959                     Why didn't u call on your lunch?
5353    Guai... Ü shd haf seen him when he's naughty.....
1888    Urgent! Please call 09061743811 from landline....
                              ...                        
5178    SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
4160             Now got tv 2 watch meh? U no work today?
1953            Nah im goin 2 the wrks with j wot bout u?
2799    Purity of friendship between two is not about ...
3900    Ü mean it's confirmed... I tot they juz say on...
Name: Message, Length: 1115, dtype: object


In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4]

2245                              No management puzzeles.
1820                Dunno dat's wat he told me. Ok lor...
642     said kiss, kiss, i can't do the sound effects!...
1726    You know there is. I shall speak to you in  &l...
Name: Message, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

2245    0
1820    0
642     0
1726    0
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

numpy.ndarray

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7733 sparse matrix of type '<class 'numpy.int64'>'
	with 58997 stored elements in Compressed Sparse Row format>

In [ ]:
type(X_train_cv)

scipy.sparse._csr.csr_matrix

In [ ]:
print(X_train_cv)

  (0, 4798)	1
  (0, 4341)	1
  (0, 5532)	1
  (1, 2481)	1
  (1, 2165)	1
  (1, 7392)	1
  (1, 3369)	1
  (1, 6947)	1
  (1, 4408)	1
  (1, 4921)	1
  (1, 4211)	1
  (2, 3369)	2
  (2, 5899)	1
  (2, 3952)	2
  (2, 1622)	1
  (2, 2370)	1
  (2, 6820)	1
  (2, 6353)	1
  (2, 2532)	1
  (2, 3754)	1
  (2, 3196)	1
  (2, 4337)	1
  (2, 3761)	1
  (2, 3943)	1
  (2, 4895)	1
  :	:
  (4455, 4171)	1
  (4456, 7694)	1
  (4456, 959)	2
  (4456, 7699)	1
  (4456, 7630)	1
  (4456, 1891)	1
  (4456, 1111)	1
  (4456, 5739)	1
  (4456, 810)	1
  (4456, 2979)	1
  (4456, 5643)	1
  (4456, 1584)	1
  (4456, 7514)	1
  (4456, 7541)	1
  (4456, 5345)	1
  (4456, 4685)	1
  (4456, 1925)	1
  (4456, 7441)	1
  (4456, 4181)	1
  (4456, 5190)	1
  (4456, 7249)	1
  (4456, 775)	1
  (4456, 3151)	1
  (4456, 5193)	1
  (4456, 69)	1


In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
print(len(X_train_cv.toarray()))

4457


In [ ]:
X_train_cv.toarray()[:5]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv.shape

(4457, 7744)

In [ ]:
v.get_feature_names_out()[4341]

'management'

In [ ]:
v.vocabulary_

{'no': 4798,
 'management': 4341,
 'puzzeles': 5532,
 'dunno': 2481,
 'dat': 2165,
 'wat': 7392,
 'he': 3369,
 'told': 6947,
 'me': 4408,
 'ok': 4921,
 'lor': 4211,
 'said': 5899,
 'kiss': 3952,
 'can': 1622,
 'do': 2370,
 'the': 6820,
 'sound': 6353,
 'effects': 2532,
 'is': 3754,
 'gorgeous': 3196,
 'man': 4337,
 'isn': 3761,
 'kind': 3943,
 'of': 4895,
 'person': 5174,
 'who': 7492,
 'needs': 4731,
 'smile': 6269,
 'to': 6932,
 'brighten': 1501,
 'his': 3439,
 'day': 2173,
 'you': 7694,
 'know': 3964,
 'there': 6837,
 'shall': 6081,
 'speak': 6375,
 'in': 3645,
 'lt': 4255,
 'gt': 3261,
 'minutes': 4503,
 'then': 6832,
 'that': 6817,
 'it': 3766,
 'bad': 1195,
 'all': 912,
 'gals': 3062,
 'doing': 2391,
 'now': 4848,
 'oh': 4917,
 'den': 2235,
 'muz': 4663,
 'change': 1717,
 'plan': 5244,
 'liao': 4104,
 'go': 3159,
 'back': 1193,
 'have': 3358,
 'yan': 7659,
 'jiu': 3834,
 'again': 859,
 'quite': 5550,
 'but': 1567,
 'dun': 2479,
 'tell': 6763,
 'him': 3432,
 'wait': 7351,
 'get': 

In [ ]:
v.vocabulary_.get("effects")

2532

In [ ]:
for i,c in v.vocabulary_.items():
  if c==2481:
    print(i)

dunno


In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[1]!=0)

(array([2165, 2481, 3369, 4211, 4408, 4921, 6947, 7392]),)

In [ ]:
X_train[1][2]

' '

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.98      1.00      0.99       951
           1       0.99      0.90      0.94       164

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [ ]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [ ]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       951
           1       0.99      0.90      0.94       164

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
%pip install gensim


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [ ]:
for i, word in enumerate(list(wv.index_to_key)):
    if i == 10:
        break
    print(word)

NameError: name 'wv' is not defined

In [ ]:
vec_king = wv['king']
print(vec_king)

[ 1.25976562e-01  2.97851562e-02  8.60595703e-03  1.39648438e-01
 -2.56347656e-02 -3.61328125e-02  1.11816406e-01 -1.98242188e-01
  5.12695312e-02  3.63281250e-01 -2.42187500e-01 -3.02734375e-01
 -1.77734375e-01 -2.49023438e-02 -1.67968750e-01 -1.69921875e-01
  3.46679688e-02  5.21850586e-03  4.63867188e-02  1.28906250e-01
  1.36718750e-01  1.12792969e-01  5.95703125e-02  1.36718750e-01
  1.01074219e-01 -1.76757812e-01 -2.51953125e-01  5.98144531e-02
  3.41796875e-01 -3.11279297e-02  1.04492188e-01  6.17675781e-02
  1.24511719e-01  4.00390625e-01 -3.22265625e-01  8.39843750e-02
  3.90625000e-02  5.85937500e-03  7.03125000e-02  1.72851562e-01
  1.38671875e-01 -2.31445312e-01  2.83203125e-01  1.42578125e-01
  3.41796875e-01 -2.39257812e-02 -1.09863281e-01  3.32031250e-02
 -5.46875000e-02  1.53198242e-02 -1.62109375e-01  1.58203125e-01
 -2.59765625e-01  2.01416016e-02 -1.63085938e-01  1.35803223e-03
 -1.44531250e-01 -5.68847656e-02  4.29687500e-02 -2.46582031e-02
  1.85546875e-01  4.47265

In [ ]:
pairs = [
    ('car', 'minivan'),   # a minivan is a kind of car
    ('car', 'bicycle'),   # still a wheeled vehicle
    ('car', 'airplane'),  # ok, no wheels, but still a vehicle
    ('car', 'cereal'),    # ... and so on
    ('car', 'communism'),
]
for w1, w2 in pairs:
    print('%r\t%r\t%.2f' % (w1, w2, wv.similarity(w1, w2)))

'car'	'minivan'	0.69
'car'	'bicycle'	0.54
'car'	'airplane'	0.42
'car'	'cereal'	0.14
'car'	'communism'	0.06


In [ ]:
print(wv.most_similar(positive=['car', 'minivan'], topn=5))

[('SUV', 0.8532192707061768), ('vehicle', 0.8175783753395081), ('pickup_truck', 0.7763688564300537), ('Jeep', 0.7567334175109863), ('Ford_Explorer', 0.7565720081329346)]


In [ ]:
print(wv.doesnt_match(['fire', 'water', 'land', 'sea', 'air', 'car']))

car


In [ ]:
# import required module
from sklearn.feature_extraction.text import TfidfVectorizer

# assign documents
d0 = 'Geeks for geeks'
d1 = 'Geeks'
d2 = 'r2j'

# merge documents into a single corpus
string = [d0, d1, d2]

# create object
tfidf = TfidfVectorizer()

# get tf-df values
result = tfidf.fit_transform(string)

# get idf values
print('\nidf values:')
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)

# get indexing
print('\nWord indexes:')
print(tfidf.vocabulary_)

# display tf-idf values
print('\ntf-idf value:')
print(result)

# in matrix form
print('\ntf-idf values in matrix form:')
print(result.toarray())


idf values:
for : 1.6931471805599454
geeks : 1.2876820724517808
r2j : 1.6931471805599454

Word indexes:
{'geeks': 1, 'for': 0, 'r2j': 2}

tf-idf value:
  (0, 1)	0.8355915419449176
  (0, 0)	0.5493512310263033
  (1, 1)	1.0
  (2, 2)	1.0

tf-idf values in matrix form:
[[0.54935123 0.83559154 0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]


In [ ]:


# assign documents
d0 = 'geek1'
d1 = 'geek2'
d2 = 'geek3'
d3 = 'geek4'

# merge documents into a single corpus
string = [d0, d1, d2, d3]

# create object
tfidf = TfidfVectorizer()

# get tf-df values
result = tfidf.fit_transform(string)

# get indexing
print('\nWord indexes:')
print(tfidf.vocabulary_)

# display tf-idf values
print('\ntf-idf values:')
print(result)


Word indexes:
{'geek1': 0, 'geek2': 1, 'geek3': 2, 'geek4': 3}

tf-idf values:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
tokenized_sentence = [["Hello","This","is","Python","training","by","Aman"],["Hello","This","is","Java","training","by","Aman"],["Hello","This","is","Data science","training","by","Aman"],["Hello","This","is","Programming","training"]]

In [ ]:
from gensim.models import Word2Vec
mymodel = Word2Vec(tokenized_sentence, min_count=1)

In [ ]:
print(mymodel)

Word2Vec<vocab=10, vector_size=100, alpha=0.025>


In [ ]:
words = list(mymodel.wv.index_to_key)
print(words)

['training', 'is', 'This', 'Hello', 'Aman', 'by', 'Programming', 'Data science', 'Java', 'Python']


In [ ]:
print((mymodel.wv['training']).shape)

(100,)


In [ ]:
print(mymodel.wv['training'])

[-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -1.5080082e-03  2.46979

In [ ]:
mymodel.wv.most_similar("Data science")

[('training', 0.09292534738779068),
 ('Programming', 0.004845096729695797),
 ('This', -0.002748486353084445),
 ('Hello', -0.01365734077990055),
 ('Aman', -0.028450384736061096),
 ('by', -0.05773789808154106),
 ('Python', -0.0932774618268013),
 ('is', -0.11555371433496475),
 ('Java', -0.14454609155654907)]

In [ ]:
mymodel.wv.most_similar("Hello")

[('by', 0.1314900666475296),
 ('Java', 0.07497554272413254),
 ('is', 0.06797594577074051),
 ('Programming', 0.041577327996492386),
 ('This', -0.01351486798375845),
 ('Data science', -0.013657335191965103),
 ('Aman', -0.044585250318050385),
 ('training', -0.111671581864357),
 ('Python', -0.16937044262886047)]

In [ ]:
sent = ['Hello,how are you','how are you','how are you doing','i am doing great','i am doing good','i am doing']

In [ ]:
sent_labels = np.array([1,1,1,0,0,0])

In [ ]:
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in sent]
print(encoded_sent)

[[8, 18, 14, 6], [18, 14, 6], [18, 14, 6, 22], [13, 15, 22, 1], [13, 15, 22, 18], [13, 15, 22]]


In [ ]:
length = 5
padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre')
print(padded_sent)

[[ 0  8 18 14  6]
 [ 0  0 18 14  6]
 [ 0 18 14  6 22]
 [ 0 13 15 22  1]
 [ 0 13 15 22 18]
 [ 0  0 13 15 22]]


In [ ]:
mymodel = Sequential()
mymodel.add(Embedding(my_vocab_size, 8, input_length=length))
mymodel.add(Flatten())
mymodel.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
mymodel.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics=['accuracy'])
mymodel.fit(padded_sent, sent_labels, epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.1667 - loss: 0.7008
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6937
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6902
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6867
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6832
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6798
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8333 - loss: 0.6763
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.6729
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.6694
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 1.0000 - loss: 0.6660
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 1.0000 - loss: 0.6626
Epo

In [ ]:
loss,accuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)
print('Accuracy: %f' %(accuracy*100))

Accuracy: 100.000000


In [ ]:
sent_to_predict = ['How are you suman','i am bad']

In [ ]:
my_vocab_size = 30
encoded_sent = [one_hot(i, my_vocab_size) for i in sent_to_predict]
print(encoded_sent)

[[18, 14, 6, 7], [13, 15, 18]]


In [ ]:
max_length = 5
padded_pred = pad_sequences(encoded_sent, maxlen = max_length, padding='pre')
print(padded_pred)

[[ 0 18 14  6  7]
 [ 0  0 13 15 18]]


In [ ]:
x = mymodel.predict(padded_pred)
classes_x=np.argmax(x,axis=1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


In [ ]:
print(classes_x)

[0 0]


In [ ]:
y = (mymodel.predict(padded_pred) > 0.5).astype("int32")
print(y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[1]
 [0]]


In [ ]:
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)
model.save("word2vec.model")

ModuleNotFoundError: No module named 'gensim'

In [ ]:
model = Word2Vec.load("word2vec.model")
model.train([["hello", "world"]], total_examples=1, epochs=1)

(0, 2)

In [ ]:
vector = model.wv['computer']
sims = model.wv.most_similar('computer', topn=10)

In [ ]:
from gensim.models import KeyedVectors

word_vectors = model.wv
word_vectors.save("word2vec.wordvectors")
wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')

vector = wv['computer']

In [ ]:
from gensim.test.utils import datapath

wv_from_text = KeyedVectors.load_word2vec_format(datapath('word2vec_pre_kv_c'), binary=False)
wv_from_bin = KeyedVectors.load_word2vec_format(datapath("euclidean_vectors.bin"), binary=True)

In [ ]:
word_vectors = model.wv

In [ ]:
print(word_vectors)

KeyedVectors<vector_size=100, 12 keys>


In [ ]:
from gensim.models.phrases import Phrases, Phraser
bigram_transformer = Phrases(common_texts)
model = Word2Vec(bigram_transformer[common_texts], min_count=1)

In [ ]:
import gensim.downloader

print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [ ]:
glove_vectors = gensim.downloader.load('glove-twitter-25')

In [ ]:
glove_vectors.most_similar('twitter')

[('facebook', 0.948005199432373),
 ('tweet', 0.9403423070907593),
 ('fb', 0.9342358708381653),
 ('instagram', 0.9104824066162109),
 ('chat', 0.8964964747428894),
 ('hashtag', 0.8885937333106995),
 ('tweets', 0.8878158330917358),
 ('tl', 0.8778461217880249),
 ('link', 0.8778210878372192),
 ('internet', 0.8753897547721863)]

In [ ]:
import numpy as np
from scipy.sparse import csr_matrix

# Create a sparse matrix
sparse_mat = csr_matrix([[0, 0, 1], [1, 0, 0], [0, 0, 2]])

# Convert to a dense NumPy array
print(sparse_mat)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	1
  (1, 0)	1
  (2, 2)	2
